drop table customer;

CREATE TABLE `customer` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `first_name` varchar(45) DEFAULT NULL,
  `last_name` varchar(45) DEFAULT NULL,
  `email` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;


INSERT INTO customer (first_name, last_name, email)
VALUES
  ('Aarav', 'Sharma', 'aarav.sharma@example.com'),
  ('Bhavya', 'Patel', 'bhavya.patel@example.com'),
  ('Chirag', 'Singh', 'chirag.singh@example.com'),
  ('Amit', 'Gupta', 'amit.gupta@example.com'),
  ('Bhavna', 'Sinha', 'bhavna.sinha@example.com'),
  ('Chitra', 'Kaur', 'chitra.kaur@example.com'),
  ('Anjali', 'Rao', 'anjali.rao@example.com'),
  ('Bhavesh', 'Shah', 'bhavesh.shah@example.com'),
  ('Chandni', 'Chopra', 'chandni.chopra@example.com'),
  ('Ankit', 'Kumar', 'ankit.kumar@example.com'),
  ('Bharat', 'Jain', 'bharat.jain@example.com'),
  ('Chetan', 'Gandhi', 'chetan.gandhi@example.com'),
  ('Anshul', 'Yadav', 'anshul.yadav@example.com'),
  ('Bhargavi', 'Reddy', 'bhargavi.reddy@example.com'),
  ('Chaitanya', 'Pandey', 'chaitanya.pandey@example.com'),
  ('Ayesha', 'Hussain', 'ayesha.hussain@example.com'),
  ('Bilal', 'Malik', 'bilal.malik@example.com'),
  ('Cynthia', 'Srivastava', 'cynthia.srivastava@example.com'),
  ('Avinash', 'Verma', 'avinash.verma@example.com'),
  ('Binod', 'Kumar', 'binod.kumar@example.com'),
  ('Gaurav', 'Sharma', 'gaurav.sharma@example.com'),
  ('Meera', 'Patel', 'meera.patel@example.com'),
  ('Shubham', 'Singh', 'shubham.singh@example.com'),
  ('Gopal', 'Gupta', 'gopal.gupta@example.com'),
  ('Manisha', 'Sinha', 'manisha.sinha@example.com'),
  ('Saurabh', 'Kaur', 'saurabh.kaur@example.com'),
  ('Gitanjali', 'Rao', 'gitanjali.rao@example.com'),
  ('Mayank', 'Shah', 'mayank.shah@example.com'),
  ('Sadhana', 'Chopra', 'sadhana.chopra@example.com'),
  ('Gauri', 'Kumar', 'gauri.kumar@example.com'),
  ('Mukesh', 'Jain', 'mukesh.jain@example.com'),
  ('Shashank', 'Gandhi', 'shashank.gandhi@example.com'),
  ('Girish', 'Yadav', 'girish.yadav@example.com'),
  ('Manoj', 'Reddy', 'manoj.reddy@example.com'),
  ('Sarika', 'Pandey', 'sarika.pandey@example.com'),
  ('Garima', 'Hussain', 'garima.hussain@example.com'),
  ('Mohit', 'Malik', 'mohit.malik@example.com'),
  ('Swati', 'Srivastava', 'swati.srivastava@example.com'),
  ('Ganesh', 'Verma', 'ganesh.verma@example.com'),
  ('Mridul', 'Kumar', 'mridul.kumar@example.com'),
  ('Sneha', 'Jha', 'sneha.jha@example.com'),
  ('Geeta', 'Shukla', 'geeta.shukla@example.com'),
  ('Mahesh', 'Pandit', 'mahesh.pandit@example.com'),
  ('Suman', 'Rawat', 'suman.rawat@example.com'),
  ('Smita', 'Shinde', 'smita.shinde@example.com'),
  ('Pooja', 'Srivastava', 'pooja.srivastava@example.com'),
  ('Rahul', 'Mishra', 'rahul.mishra@example.com'),
  ('Kavita', 'Singh', 'kavita.singh@example.com'),
  ('Rohan', 'Verma', 'rohan.verma@example.com'),
  ('Komal', 'Sharma', 'komal.sharma@example.com'),
  ('Rajesh', 'Jain', 'rajesh.jain@example.com'),
  ('Priyanka', 'Thakur', 'priyanka.thakur@example.com'),
  ('Kirti', 'Gupta', 'kirti.gupta@example.com'),
  ('Prateek', 'Chopra', 'prateek.chopra@example.com'),
  ('Ruchi', 'Patel', 'ruchi.patel@example.com'),
  ('Kunal', 'Shah', 'kunal.shah@example.com'),
  ('Pratiksha', 'Joshi', 'pratiksha.joshi@example.com'),
  ('Kanika', 'Bhatnagar', 'kanika.bhatnagar@example.com'),
  ('Rakesh', 'Kumar', 'rakesh.kumar@example.com'),
  ('Pramod', 'Shinde', 'pramod.shinde@example.com'),
  ('Ritu', 'Mehra', 'ritu.mehra@example.com'),
  ('Kamal', 'Yadav', 'kamal.yadav@example.com'),
  ('Preeti', 'Malik', 'preeti.malik@example.com'),
  ('Kunal', 'Jha', 'kunal.jha@example.com'),
  ('Riya', 'Choudhary', 'riya.choudhary@example.com'),
  ('Krishna', 'Nair', 'krishna.nair@example.com'),
  ('Pawan', 'Sinha', 'pawan.sinha@example.com'),
  ('Rupali', 'Deshpande', 'rupali.deshpande@example.com'),
  ('Kajal', 'Mehta', 'kajal.mehta@example.com'),
  ('Pallavi', 'Kapoor', 'pallavi.kapoor@example.com'),
   ('Neha', 'Sharma', 'neha.sharma@example.com'),
  ('Tarun', 'Joshi', 'tarun.joshi@example.com'),
  ('Jaya', 'Singh', 'jaya.singh@example.com'),
  ('Nikhil', 'Chopra', 'nikhil.chopra@example.com'),
  ('Tina', 'Rai', 'tina.rai@example.com'),
  ('Jatin', 'Shah', 'jatin.shah@example.com'),
  ('Nidhi', 'Gupta', 'nidhi.gupta@example.com'),
  ('Tanvi', 'Mehta', 'tanvi.mehta@example.com'),
  ('Jatin', 'Patel', 'jatin.patel@example.com'),
  ('Nikita', 'Kapoor', 'nikita.kapoor@example.com'),
  ('Tarun', 'Nair', 'tarun.nair@example.com'),
  ('Jasmine', 'Khan', 'jasmine.khan@example.com'),
  ('Nisha', 'Bhatnagar', 'nisha.bhatnagar@example.com'),
  ('Tanmay', 'Chakraborty', 'tanmay.chakraborty@example.com'),
  ('Jatin', 'Gandhi', 'jatin.gandhi@example.com'),
  ('Nitin', 'Deshpande', 'nitin.deshpande@example.com'),
  ('Tanya', 'Sinha', 'tanya.sinha@example.com'),
  ('Jhanvi', 'Mehra', 'jhanvi.mehra@example.com'),
  ('Namrata', 'Jain', 'namrata.jain@example.com'),
  ('Tushar', 'Malik', 'tushar.malik@example.com'),
  ('Jyoti', 'Verma', 'jyoti.verma@example.com'),
  ('Nehal', 'Thakur', 'nehal.thakur@example.com'),
  ('Tara', 'Bhandari', 'tara.bhandari@example.com'),
  ('Jaspreet', 'Kaur', 'jaspreet.kaur@example.com'),
  ('Navya', 'Rajput', 'navya.rajput@example.com');
  

